### ISSUE TITLE
Is there a reason why `haphazard::AtomicPtr` is not `Send + Sync`?

### ISSUE THREAD

**Issue by zjijz** [jonhoo/haphazard#30]
Forgive me if this is a dumb question, but why isn't `haphazard::AtomicPtr` `Send + Sync` when `std::sync::atomic::AtomicPtr` is both?

There are really two questions here:
- Why isn't `haphazard::AtomicPtr` `Send`?
- Why isn't `haphazard::AtomicPtr` `Sync`?

For the first, I was confused when `!Send` was shown in the docs since the struct doc states `haphazard::AtomicPtr` is meant to be safe to share between threads (https://github.com/jonhoo/haphazard/blob/55f1078942f02636ecfe52ffa6b264297c23bf07/src/lib.rs#L185).

For the second, is there a technical reason why `Sync` should not be available based on the current implementation of `haphazard::AtomicPtr`? I am in the process of reading the paper and watching your video series on this crate, but I do not have enough intuition right now as to why it would not be `Sync` safe.

From what I could tell the reason why both `!Send` and `!Sync` are being auto-implemented is that`*mut P` is being used in `PhantomData` (https://github.com/jonhoo/haphazard/blob/55f1078942f02636ecfe52ffa6b264297c23bf07/src/lib.rs#L237) and all raw pointers are marked as `!Send + !Sync`. What was the reasoning as to why `*mut P` needed to be put into `PhantomData` instead of just `P`?

Thank you in advance!

**Comment by jonhoo** [comment]
Nope, that's definitely just an oversight on my part! If you want to submit a PR fixing it, go for it! :+1:

**Comment by zjijz** [comment]
@jonhoo Just pushed the fix I was using locally with #31 . Let me know if you need anything else!
