### ISSUE TITLE
Load/store raw pointers

### ISSUE THREAD

**Issue by ibraheemdev** [jonhoo/haphazard#33]
The new API makes it easy to load shared references and store newly allocated elements, but makes impossible to load a `*mut T` valid for deallocation, which is needed for data-structures like a Treiber stack. I don't think it is currently possible to implement a Treiber stack correctly with haphazard.

**Comment by jonhoo** [comment]
I'm not sure I follow? The old API is still there in `haphazard::raw`, and the higher-level `AtomicPtr` API has methods like `load_ptr` which I _think_ does what you need. Or am I missing something?

**Comment by ibraheemdev** [comment]
Ah, I missed `HazardPointer::protect_ptr`, that works :+1:
