### ISSUE TITLE
Clarification of invalid operations in tests/lib.rs

### ISSUE THREAD

**Issue by emilHof** [jonhoo/haphazard#41]
I was reading through the tests to better understand how tho use the crate, when i came across this line that confused me:
```rust
58    drop(hazptr_array);
59    // invalid:
60    // let _: i32 = my_y.0;
61    // invalid:
62    // let _: i32 = my_y.0;
```
It confused me a bit and I was wondering if this meant to say `let: _: i32 = my_x.0`  for one of the comments? I hope this is not a super annoying question haha!

**Comment by jonhoo** [comment]
Pro-tip: if you mark the lines in the GitHub code view, press `y`, and then paste that link, you get a code snippet that links back to the code:
https://github.com/jonhoo/haphazard/blob/6bcebbd3f6ad13366c5c3a01081d60483c08768b/tests/lib.rs#L58-L62

But yes, you're entirely right, one of those should read `my_x.0`! Want to cut a PR?

**Comment by emilHof** [comment]
> Pro-tip: if you mark the lines in the GitHub code view, press y, and then paste that link, you get a code snippet that links back to the code:
Wow, that is awesome! I did not know this existed, thank you haha!

Yess, I definitely can! In the end it was a kind of nit-picky and probably quite unimportant thing to point out haha!

**Comment by jonhoo** [comment]
In a library this low level where the details matter so much, I think it's very much worth fixing!

**Comment by emilHof** [comment]
Haha, I definitely appreciate your support of my very minuscule contribution ! :)
